autopkgtest: Check if upgrading in minimal steps is the default

diff --git a/debian/tests/upgrade-between-snapshots b/debian/tests/upgrade-between-snapshots
--- a/debian/tests/upgrade-between-snapshots
+++ b/debian/tests/upgrade-between-snapshots
@@ -51,6 +51,10 @@ sed -i "s/$start_date/$end_date/" "$chroot_dir/etc/apt/sources.list"
 
 run_u_u "$chroot_dir"
 
+echo "Upgrade should be performed in minimal steps, checking that..."
+grep -q "left to upgrade {" "$chroot_dir"/var/log/unattended-upgrades/unattended-upgrades.log || \
+    (echo "FAILED: Upgrade was performed in a single step." ; exit 1)
+
 echo "libpoppler68 should be still installed and held:"
 chroot_exec "$chroot_dir" dpkg -l libpoppler68 | grep '^hi'
 
