Fix the systemd unit so it runs as an ExecStop and do not block when /var is separate
* Non-maintainer upload.
* Fix the unattended-upgrades.service unit not correctly working:
  - d/rules : Remove the override_dh_installinit. The stop option is no longer
    available so the command falls back to default. This is the normal
    behavior so the override is not required
  - d/unattended-upgrades.init : Add Default-Start runlevels, otherwise the
    unattended-upgrades.service unit cannot be enabled on boot
  - d/postinst : Cleanup the stop symlinks created by the wrong
    override_dh_installinit. Without that, the systemd unit cannot be
    enabled correctly.
    Force disable the service before deb-systemd-helper runs so the old
    symlink is not left dangling (workaround for Debian Bug #797108).
    Force enable and start of the systemd unit to work around Debian Bug
    #797108 which fails to enable systemd units correctly when WantedBy=
    statement is changed which is the case here.
  - d/unattended-upgrades.service : Fix the service so it runs correctly on
    shutdown :
      Remove DefaultDependencies=no : Breaks normal shutdown dependencies
      Set After= to network.target and local-fs.target. Since our service is
      now ExecStop, it will run before network and local-fs become
      unavailable. Add RequiresMountsFor=/var/log /var/run /var/lib /boot :
      Necessary if /var is a separate file system. Set WantedBy= to
      multi-user.target
  - Add DEP8 tests to verify the following :
    Verify that the unattended-upgrades.service unit is enabled and started.
    Verify that InstallOnShutdown works when configured.
  (Closes: #809669)

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -61,6 +61,20 @@ case "$1" in
             && [ -f /etc/rc6.d/S[0-9][0-9]unattended-upgrades ] ; then
             update-rc.d -f unattended-upgrades remove
         fi
+        # Recover from broken dh_installinit override in versions < 0.93.1+nmu1
+        if dpkg --compare-versions "$2" lt "0.93.1+nmu1"; then
+            if [ -f /etc/rc0.d/K[0-9][0-9]unattended-upgrades ] \
+            && [ -f /etc/rc6.d/K[0-9][0-9]unattended-upgrades ] ; then
+            	update-rc.d -f unattended-upgrades remove
+	    fi
+	    # If running systemd, explicitely disable the service otherwise
+	    # the shutdown.target symlink will remain (See Debian Bug #797108)
+	    if [ -d /run/systemd/system ]; then
+	        if deb-systemd-helper --quiet was-enabled unattended-upgrades.service; then
+	            deb-systemd-helper disable unattended-upgrades.service >/dev/null || true
+	        fi
+	    fi
+	fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -77,6 +91,21 @@ esac
 
 #DEBHELPER#
 
+# Explicitly enable and start the service. Debian Bug #797108 for 
+# deb-systemd-helper fails to correctly enable the unit. It checks for 
+# enablement using the content of the WantedBy= which has changed so it
+# sees the service as disable and will not enable it.
+case "$1" in
+    configure)
+        if dpkg --compare-versions "$2" lt "0.93.1+nmu1" \
+	&& [ -d /run/systemd/system ]; then
+                # workaround systemd bug with enable --now which
+                # fails to start the unit
+		systemctl enable unattended-upgrades || true
+		systemctl start unattended-upgrades || true
+	fi
+    ;;
+esac
 exit 0
 
 
