Revert "Run unattended-upgrades.service before shutdown.target as a oneshot service"
This reverts commit cda637b0d89973fd46382418893a23bef4195a2f.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -66,11 +66,8 @@ case "$1" in
             && [ -f /etc/rc6.d/K[0-9][0-9]unattended-upgrades ] ; then
             	update-rc.d -f unattended-upgrades remove
 	    fi
-	fi
-        if ([ "$(lsb_release -i -s)" != "Ubuntu" ] && dpkg --compare-versions "$2" lt "1.5~") || \
-               ([ "$(lsb_release -i -s)" = "Ubuntu" ] && dpkg --compare-versions "$2" lt "1.5ubuntu1~"); then
 	    # If running systemd, explicitely disable the service otherwise
-	    # the multi-user.target symlink will remain (See Debian Bug #797108)
+	    # the shutdown.target symlink will remain (See Debian Bug #797108)
 	    if [ -d /run/systemd/system ]; then
 	        if deb-systemd-helper --quiet was-enabled unattended-upgrades.service; then
 	            deb-systemd-helper disable unattended-upgrades.service >/dev/null || true
@@ -93,16 +90,19 @@ esac
 
 #DEBHELPER#
 
-# Explicitly enable the service. Debian Bug #797108 for
-# deb-systemd-helper fails to correctly enable the unit. It checks for
+# Explicitly enable and start the service. Debian Bug #797108 for 
+# deb-systemd-helper fails to correctly enable the unit. It checks for 
 # enablement using the content of the WantedBy= which has changed so it
 # sees the service as disable and will not enable it.
 case "$1" in
     configure)
-        if ( ([ "$(lsb_release -i -s)" != "Ubuntu" ] && dpkg --compare-versions "$2" lt "1.5~") || \
-                 ([ "$(lsb_release -i -s)" = "Ubuntu" ] && dpkg --compare-versions "$2" lt "1.5ubuntu1~") )\
+        if ( ([ "$(lsb_release -i -s)" != "Ubuntu" ] && dpkg --compare-versions "$2" lt "0.93.1+nmu1") || \
+                 ([ "$(lsb_release -i -s)" = "Ubuntu" ] && dpkg --compare-versions "$2" lt "0.93.1ubuntu3") )\
 	       && [ -d /run/systemd/system ]; then
+                # workaround systemd bug with enable --now which
+                # fails to start the unit
 		systemctl enable unattended-upgrades || true
+		deb-systemd-invoke start unattended-upgrades.service || true
 	fi
     ;;
 esac
